### ISSUE TITLE
ORA-01017: invalid username/password; logon denied

### ISSUE THREAD

**Issue by miklblitz** [apaoww/yii2-oci8#2]
I configured db.php for my yii2 project.

```
return [
    'class' => 'apaoww\oci8\Oci8DbConnection',
    'dsn' => 'oci8:dbname=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=MY_ORACLE_DB_IP)(PORT=1521))(CONNECT_DATA=(SID=MASTERS)));charset=AL32UTF8;',
    'username' => 'MSK_MASTERS',
    'password' => 'MSK_MASTERS',
    'attributes' => [
        PDO::ATTR_STRINGIFY_FETCHES => true,
    ]
];
```

but I got error:
`Creating migration history table "migration"...Exception 'yii\db\Exception' with message 'ORA-01017: invalid username/password; logon denied'`

But username && password are correct. Where i done error.

**Comment by miklblitz** [comment]
Sorry, password was incorrect. Issue closed :).

**Comment by apaoww** [comment]
I am glade you solve the problem.
