### ISSUE TITLE
must be changed to yii\db\ExpressionInterface

### ISSUE THREAD

**Issue by gobsek** [apaoww/yii2-oci8#9]
https://github.com/apaoww/yii2-oci8/blob/e947ae592656026afb745025d1d27ad32648f0c4/QueryBuilder.php#L183

**Comment by sinelnikof88** [comment]
> https://github.com/apaoww/yii2-oci8/blob/e947ae592656026afb745025d1d27ad32648f0c4/QueryBuilder.php#L183

Костыль https://yadi.sk/d/yH2PcdvfqwObeg

**Comment by apaoww** [comment]
Already changed.
